# Use postgres/example user/password credentials

services:

  postgres-cotacao:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
